services:
  chatbot_app:
    image: ${DOCKER_REPO}/chatbot_app
    container_name: chatbot_app
    restart: always
    #ports:
    #  - "3000:3000"
    networks:
      - deploy_my_network
  llm_app:
    image: ${DOCKER_REPO}/llm_app
    container_name: llm_app
    restart: always
    #ports:
    #  - "3001:3001"
    networks:
      - deploy_my_network
networks:
  deploy_my_network:
    external: true
    name: my_network
  int-network1:
    name: int-network1

