services:
  chatbot_app:
    image: chatbot_app
    container_name: chatbot_app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - int_network
 #     - int-network1
  llm_app:
    image: llm_app
    container_name: llm_app
    hostname: llm_app
    restart: always
    volumes:
      - ./aws:/root/.aws
      - ./kb:/app/kb
      - ./config.ini:/app/config.ini
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks:
      - int_network
 #     - int-network1

  postgres:
    image: ankane/pgvector  # This image includes Postgres with pgvector
    container_name: postgres-vector
    hostname: postgres-vector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - int_network
volumes:
  postgres_data: {}
  kb: {}

networks:
  int_network:
    driver: bridge
    #external: true
    #name: ext_network
#  int-network1:
#    name: int-network1

